/* 文字コードはＳＪＩＳ 改行コードはＣＲＬＦ */
/* $Id$ */


#define DEFINE_DMOENCODER_CLSID(fcc, fccname) \
	DEFINE_GUID(CLSID_##fccname##DMOEncoder, fcc, 0xE991, 0x460D, 0x84, 0x0B, 0xC1, 0xC6, 0x49, 0x74, 0x57, 0xEF)

DEFINE_DMOENCODER_CLSID(FCC('ULRA'), ULRA);
DEFINE_DMOENCODER_CLSID(FCC('ULRG'), ULRG);
DEFINE_DMOENCODER_CLSID(FCC('ULY0'), ULY0);
DEFINE_DMOENCODER_CLSID(FCC('ULY2'), ULY2);
