/* ï∂éöÉRÅ[ÉhÇÕÇrÇiÇhÇr â¸çsÉRÅ[ÉhÇÕÇbÇqÇkÇe */
/* $Id$ */

#include "stdafx.h"
#include "utvideo.h"
#include "TunedFunc.h"
#include "Predict.h"
#include "HuffmanCode.h"
#include "Convert.h"

const TUNEDFUNC tfnI686 = {
	cpp_PredictWrongMedianAndCount,
	cpp_PredictWrongMedianAndCount,
	cpp_PredictLeftAndCount,
	x86_i686_RestoreWrongMedian_align1,
	x86_i686_HuffmanEncode,
	x86_i686_HuffmanDecode,
	x86_i686_HuffmanDecodeAndAccum,
	x86_i686_HuffmanDecodeAndAccumStep2,
	x86_i686_HuffmanDecodeAndAccumStep4,
	x86_i686_HuffmanDecodeAndAccumStep4ForBottomupBGRXGreen,
	x86_i686_HuffmanDecodeAndAccumStep4ForBottomupBGRXBlue,
	x86_i686_HuffmanDecodeAndAccumStep4ForBottomupBGRXRed,
	x86_i686_HuffmanDecodeAndAccumStep4ForBottomupBGRXRedAndDummyAlpha,
	x86_i686_HuffmanDecodeAndAccumStep3ForBottomupBGRGreen,
	x86_i686_HuffmanDecodeAndAccumStep3ForBottomupBGRBlue,
	x86_i686_HuffmanDecodeAndAccumStep3ForBottomupBGRRed,
	x86_i686_HuffmanDecodeAndAccumStep4ForTopdownXRGBGreen,
	x86_i686_HuffmanDecodeAndAccumStep4ForTopdownXRGBBlue,
	x86_i686_HuffmanDecodeAndAccumStep4ForTopdownXRGBRed,
	x86_i686_HuffmanDecodeAndAccumStep4ForTopdownXRGBRedAndDummyAlpha,
	x86_i686_HuffmanDecodeAndAccumStep3ForTopdownRGBGreen,
	x86_i686_HuffmanDecodeAndAccumStep3ForTopdownRGBBlue,
	x86_i686_HuffmanDecodeAndAccumStep3ForTopdownRGBRed,
	x86_i686_HuffmanDecodeAndAccumStep4ForTopdownBGRXRedAndDummyAlpha,
	cpp_ConvertULY2ToBGR,
	cpp_ConvertULY2ToBGRX,
	cpp_ConvertULY2ToRGB,
	cpp_ConvertULY2ToXRGB,
	cpp_ConvertBGRToULY2,
	cpp_ConvertBGRXToULY2,
	cpp_ConvertRGBToULY2,
	cpp_ConvertXRGBToULY2,
	cpp_ConvertBGRToULRG,
	cpp_ConvertBGRXToULRG,
	cpp_ConvertXRGBToULRG,
	cpp_ConvertBGRAToULRA,
	cpp_ConvertARGBToULRA,
	cpp_ConvertYUYVToULY2,
	cpp_ConvertUYVYToULY2,
	cpp_ConvertULRGToBGR,
	cpp_ConvertULRGToBGRX,
	cpp_ConvertULRGToXRGB,
	cpp_ConvertULRAToBGRA,
	cpp_ConvertULRAToARGB,
	cpp_ConvertULY2ToYUYV,
	cpp_ConvertULY2ToUYVY,
	DummyTunedFunc
};

const TUNEDFUNC tfnSSE2 = {
	x86_sse2_PredictWrongMedianAndCount_align16,
	x86_sse2_PredictWrongMedianAndCount_align1,
	x86_sse2_PredictLeftAndCount_align1,
	x86_sse1mmx_RestoreWrongMedian_align1,
	x86_i686_HuffmanEncode,
	x86_i686_HuffmanDecode,
	x86_i686_HuffmanDecodeAndAccum,
	x86_i686_HuffmanDecodeAndAccumStep2,
	x86_i686_HuffmanDecodeAndAccumStep4,
	x86_i686_HuffmanDecodeAndAccumStep4ForBottomupBGRXGreen,
	x86_i686_HuffmanDecodeAndAccumStep4ForBottomupBGRXBlue,
	x86_i686_HuffmanDecodeAndAccumStep4ForBottomupBGRXRed,
	x86_i686_HuffmanDecodeAndAccumStep4ForBottomupBGRXRedAndDummyAlpha,
	x86_i686_HuffmanDecodeAndAccumStep3ForBottomupBGRGreen,
	x86_i686_HuffmanDecodeAndAccumStep3ForBottomupBGRBlue,
	x86_i686_HuffmanDecodeAndAccumStep3ForBottomupBGRRed,
	x86_i686_HuffmanDecodeAndAccumStep4ForTopdownXRGBGreen,
	x86_i686_HuffmanDecodeAndAccumStep4ForTopdownXRGBBlue,
	x86_i686_HuffmanDecodeAndAccumStep4ForTopdownXRGBRed,
	x86_i686_HuffmanDecodeAndAccumStep4ForTopdownXRGBRedAndDummyAlpha,
	x86_i686_HuffmanDecodeAndAccumStep3ForTopdownRGBGreen,
	x86_i686_HuffmanDecodeAndAccumStep3ForTopdownRGBBlue,
	x86_i686_HuffmanDecodeAndAccumStep3ForTopdownRGBRed,
	x86_i686_HuffmanDecodeAndAccumStep4ForTopdownBGRXRedAndDummyAlpha,
	x86_sse2_ConvertULY2ToBGR,
	x86_sse2_ConvertULY2ToBGRX,
	x86_sse2_ConvertULY2ToRGB,
	x86_sse2_ConvertULY2ToXRGB,
	x86_sse2_ConvertBGRToULY2,
	x86_sse2_ConvertBGRXToULY2,
	x86_sse2_ConvertRGBToULY2,
	x86_sse2_ConvertXRGBToULY2,
	cpp_ConvertBGRToULRG,
	cpp_ConvertBGRXToULRG,
	cpp_ConvertXRGBToULRG,
	cpp_ConvertBGRAToULRA,
	cpp_ConvertARGBToULRA,
	cpp_ConvertYUYVToULY2,
	cpp_ConvertUYVYToULY2,
	cpp_ConvertULRGToBGR,
	cpp_ConvertULRGToBGRX,
	cpp_ConvertULRGToXRGB,
	cpp_ConvertULRAToBGRA,
	cpp_ConvertULRAToARGB,
	cpp_ConvertULY2ToYUYV,
	cpp_ConvertULY2ToUYVY,
	DummyTunedFunc
};

const TUNEDFUNC &tfnSSE3 = tfnSSE2;

const TUNEDFUNC &tfnSSSE3 = tfnSSE2;

const TUNEDFUNC &tfnSSE41 = tfnSSE2;

const TUNEDFUNC &tfnSSE42 = tfnSSE2;

const TUNEDFUNC tfnAVX1 = {
	x86_sse2_PredictWrongMedianAndCount_align16,
	x86_sse2_PredictWrongMedianAndCount_align1,
	x86_sse2_PredictLeftAndCount_align1,
	x86_sse1mmx_RestoreWrongMedian_align1,
	x86_i686_HuffmanEncode,
	x86_i686_HuffmanDecode,
	x86_i686_HuffmanDecodeAndAccum,
	x86_i686_HuffmanDecodeAndAccumStep2,
	x86_i686_HuffmanDecodeAndAccumStep4,
	x86_i686_HuffmanDecodeAndAccumStep4ForBottomupBGRXGreen,
	x86_i686_HuffmanDecodeAndAccumStep4ForBottomupBGRXBlue,
	x86_i686_HuffmanDecodeAndAccumStep4ForBottomupBGRXRed,
	x86_i686_HuffmanDecodeAndAccumStep4ForBottomupBGRXRedAndDummyAlpha,
	x86_i686_HuffmanDecodeAndAccumStep3ForBottomupBGRGreen,
	x86_i686_HuffmanDecodeAndAccumStep3ForBottomupBGRBlue,
	x86_i686_HuffmanDecodeAndAccumStep3ForBottomupBGRRed,
	x86_i686_HuffmanDecodeAndAccumStep4ForTopdownXRGBGreen,
	x86_i686_HuffmanDecodeAndAccumStep4ForTopdownXRGBBlue,
	x86_i686_HuffmanDecodeAndAccumStep4ForTopdownXRGBRed,
	x86_i686_HuffmanDecodeAndAccumStep4ForTopdownXRGBRedAndDummyAlpha,
	x86_i686_HuffmanDecodeAndAccumStep3ForTopdownRGBGreen,
	x86_i686_HuffmanDecodeAndAccumStep3ForTopdownRGBBlue,
	x86_i686_HuffmanDecodeAndAccumStep3ForTopdownRGBRed,
	x86_i686_HuffmanDecodeAndAccumStep4ForTopdownBGRXRedAndDummyAlpha,
	x86_sse2_ConvertULY2ToBGR,
	x86_sse2_ConvertULY2ToBGRX,
	x86_sse2_ConvertULY2ToRGB,
	x86_sse2_ConvertULY2ToXRGB,
	x86_sse2_ConvertBGRToULY2,
	x86_sse2_ConvertBGRXToULY2,
	x86_sse2_ConvertRGBToULY2,
	x86_sse2_ConvertXRGBToULY2,
	x86_avx1_ConvertBGRToULRG,
	x86_avx1_ConvertBGRXToULRG,
	x86_avx1_ConvertXRGBToULRG,
	x86_avx1_ConvertBGRAToULRA,
	x86_avx1_ConvertARGBToULRA,
	x86_avx1_ConvertYUYVToULY2,
	x86_avx1_ConvertUYVYToULY2,
	x86_avx1_ConvertULRGToBGR,
	x86_avx1_ConvertULRGToBGRX,
	x86_avx1_ConvertULRGToXRGB,
	x86_avx1_ConvertULRAToBGRA,
	x86_avx1_ConvertULRAToARGB,
	x86_avx1_ConvertULY2ToYUYV,
	x86_avx1_ConvertULY2ToUYVY,
	DummyTunedFunc
};

const TUNEDFUNC &tfnAVX2 = tfnAVX1;

#include "TunedFunc_x86x64.cpp"
