/* 文字コードはＳＪＩＳ 改行コードはＣＲＬＦ */
/* $Id$ */

// utv_mft.idl : utv_mft の IDL ソース
//

// このファイルは、タイプ ライブラリ (utv_mft.tlb) およびマーシャリング コードを
// 作成するために MIDL ツールによって処理されます。

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(AE0FBDA8-BB7C-42A8-BDF4-78D8F8E18D6D),
	version(1.0),
	helpstring("UtVideoMFT 1.0 type library")
]
library UtVideoMFT
{
	importlib("stdole2.tlb");
};
